version: '3'
services:
  tfs:
    build:
      context: ./
      dockerfile: ./dockerfile
      args:
        TFS_VERSION: latest
    ports:
      - "8500:8500"
      - "8501:8501"
      - "8080:8080"
    environment:
      - "RELOAD=true"
      - "ENABLE_BATCHING=true"
      - "NUM_BATCH_THREADS=16"
      - "MAX_BATCH_SIZE=1"
    #volumes:
    #  - ./build/models:/models
